port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

Proxy:
  - name: aaa
    type: vmess
    server: us1851.823km.cn
    port: "10550"
    uuid: ae9fad8c-19c0-38fa-a113-ff501a761c5d
    alterId: "0"
    cipher: auto
    network: ws
    ws-path: /v2ray
    ws-headers:
      Host: us1851.823km.cn
  - name: bbb
    type: vmess
    server: jp1518.823km.cn
    port: "10550"
    uuid: ae9fad8c-19c0-38fa-a113-ff501a761c5d
    alterId: "0"
    cipher: auto
    network: ws
    ws-path: /v2ray
    ws-headers:
      Host: jp1518.823km.cn
  - name: ccc
    type: vmess
    server: en1357.823km.cn
    port: "10550"
    uuid: ae9fad8c-19c0-38fa-a113-ff501a761c5d
    alterId: "4"
    cipher: auto
    network: ws
    ws-path: /v2ray
    ws-headers:
      Host: en1357.823km.cn
Proxy Group: []
Rule:
  - MATCH,DIRECT